/* GENERATED by build_site.py from the quotation builder's own
 * markup — never edit by hand. Prices trace to
 * 03_Package_and_Service/01_Service_Architecture.md (v1.5.1). */
export const PRICES = {
  "Proof Check": {
    "p": 1000,
    "mo": false,
    "qty": false
  },
  "Commercial Growth Signal — Core Scope": {
    "p": 3000,
    "mo": false,
    "qty": false
  },
  "Written Personas": {
    "p": 1800,
    "mo": false,
    "qty": false
  },
  "Competitive Map": {
    "p": 1000,
    "mo": false,
    "qty": false
  },
  "Measurement Reliability and the Commercial Roadmap": {
    "p": 0,
    "mo": true,
    "qty": false
  },
  "Brand Identity and Brand Book": {
    "p": 5500,
    "mo": false,
    "qty": false
  },
  "Website Design — 8 pages": {
    "p": 3500,
    "mo": false,
    "qty": false
  },
  "Custom Function Website Build — 10 pages": {
    "p": 15000,
    "mo": false,
    "qty": false
  },
  "Proposal & Presentation System": {
    "p": 5000,
    "mo": false,
    "qty": false
  },
  "Additional Website Pages": {
    "p": 500,
    "mo": false,
    "qty": true
  },
  "SEO & GEO System": {
    "p": 2000,
    "mo": true,
    "qty": false
  },
  "Google & Meta Ads, Managed": {
    "p": 1500,
    "mo": true,
    "qty": false
  },
  "AI Search Visibility": {
    "p": 1400,
    "mo": true,
    "qty": false
  },
  "Editorial Content & Case Studies": {
    "p": 2600,
    "mo": true,
    "qty": false
  },
  "Practitioner Video": {
    "p": 3500,
    "mo": true,
    "qty": false
  },
  "LinkedIn & Key-Account Outreach": {
    "p": 1000,
    "mo": true,
    "qty": false
  },
  "Email Nurture & CRM": {
    "p": 1500,
    "mo": true,
    "qty": false
  },
  "Reviews & Reputation": {
    "p": 1000,
    "mo": true,
    "qty": false
  },
  "Case Studies": {
    "p": 1800,
    "mo": false,
    "qty": true
  },
  "Campaign Sprint": {
    "p": 7500,
    "mo": false,
    "qty": false
  },
  "Vertical Sales Edition": {
    "p": 6500,
    "mo": false,
    "qty": false
  },
  "Pitch & Tender Support": {
    "p": 1900,
    "mo": false,
    "qty": false
  },
  "Art-Direction Day": {
    "p": 2200,
    "mo": false,
    "qty": false
  },
  "Strategy Session": {
    "p": 600,
    "mo": false,
    "qty": false
  }
};
export const BUNDLE = {
  "labels": [],
  "label": "",
  "price": 0
};
