/* GENERATED by build_site.py from the quotation builder's own
 * markup — never edit by hand. Prices trace to
 * 03_Package_and_Service/01_Service_Architecture.md (v1.4). */
export const PRICES = {
  "Proof Check": {
    "p": 1000,
    "mo": false,
    "qty": false
  },
  "Commercial Growth Signal — core scope": {
    "p": 3000,
    "mo": false,
    "qty": false
  },
  "Written personas": {
    "p": 1800,
    "mo": false,
    "qty": false
  },
  "Competitive map": {
    "p": 1000,
    "mo": false,
    "qty": false
  },
  "Brand identity & brand book": {
    "p": 9500,
    "mo": false,
    "qty": false
  },
  "Showcase website — 8 pages": {
    "p": 3000,
    "mo": false,
    "qty": false
  },
  "Custom-built website — 10 pages": {
    "p": 15000,
    "mo": false,
    "qty": false
  },
  "Proposal & presentation system": {
    "p": 6500,
    "mo": false,
    "qty": false
  },
  "Enquiry response & CRM setup": {
    "p": 5500,
    "mo": false,
    "qty": false
  },
  "Additional website pages": {
    "p": 350,
    "mo": false,
    "qty": true
  },
  "SEO & Local search": {
    "p": 2000,
    "mo": true,
    "qty": false
  },
  "Google & Meta ads, managed": {
    "p": 1500,
    "mo": true,
    "qty": false
  },
  "AI search visibility": {
    "p": 1400,
    "mo": true,
    "qty": false
  },
  "Editorial content & case studies": {
    "p": 2600,
    "mo": true,
    "qty": false
  },
  "Practitioner video": {
    "p": 3500,
    "mo": true,
    "qty": false
  },
  "LinkedIn & key-account outreach": {
    "p": 1000,
    "mo": true,
    "qty": false
  },
  "Email nurture & CRM": {
    "p": 1500,
    "mo": true,
    "qty": false
  },
  "Referral partner system": {
    "p": 1200,
    "mo": true,
    "qty": false
  },
  "Reviews & reputation": {
    "p": 1000,
    "mo": true,
    "qty": false
  },
  "Case studies": {
    "p": 1800,
    "mo": false,
    "qty": true
  },
  "Campaign sprint": {
    "p": 7500,
    "mo": false,
    "qty": false
  },
  "Vertical sales edition": {
    "p": 6500,
    "mo": false,
    "qty": false
  },
  "Pitch & tender support": {
    "p": 1900,
    "mo": false,
    "qty": false
  },
  "Art-direction day": {
    "p": 2200,
    "mo": false,
    "qty": false
  },
  "Strategy session": {
    "p": 600,
    "mo": false,
    "qty": false
  }
};
export const BUNDLE = {
  "labels": [
    "Brand identity & brand book",
    "Custom-built website — 10 pages",
    "Proposal & presentation system",
    "Enquiry response & CRM setup"
  ],
  "label": "Growth Foundation Build — the system",
  "price": 36500
};
