/* GENERATED by _build/build_site.py from _build/email/frame.html and
   _build/email/autoreply.html — do not edit. */

export function escapeHtml(s) {
  return String(s ?? '').replace(/[&<>"']/g, (c) => (
    { '&': '&amp;', '<': '&lt;', '>': '&gt;',
      '"': '&quot;', "'": '&#39;' }[c]));
}

/* The deadline the visitor was actually given, keyed off the
   form's own `want` field. The free report form posts
   "Free AI visibility report"; everything else is an enquiry. */
export function promise(d) {
  return /ai visibility report/i.test(String((d && d.want) || ''))
    ? 'Your free AI visibility report lands in your inbox within 24 hours.'
    : 'A named person replies within one business day.';
}

/* THE ONE FRAME. Every transactional email is this around a body of
   <tr>s: ink masthead with the lockup and the acid rail, the kicker
   in the label voice, the title in the heading voice, the body, the
   ink footer with the site's sign-off and the locked NAP. Callers
   pass ALREADY-ESCAPED strings for preheader/kicker/title/footnote
   and trusted markup for body. `title_text` is the plain title for
   <title>; it defaults to `title`. */
export function frame(p) {
  p = Object.assign({ preheader: '', kicker: '', title: '', body: '', footnote: '' }, p);
  if (p.title_text == null) p.title_text = p.title;
  return `<!doctype html>
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="x-apple-disable-message-reformatting">
<meta name="color-scheme" content="light">
<meta name="supported-color-schemes" content="light">
<title>${p.title_text}</title>
<!--[if mso]>
<xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml>
<![endif]-->
<style>
  /* Progressive enhancement only — everything that matters is inlined, because
     Gmail strips <style> in forwarded messages. */
  @media only screen and (max-width:620px){
    .wrap{width:100% !important}
    .px{padding-left:24px !important;padding-right:24px !important}
    .stack{display:block !important;width:100% !important;padding-right:0 !important}
    .stack-gap{padding-top:16px !important}
  }
  /* the site's phone h1 — same breakpoint, same clamp (site.css @media (max-width:560px) .display, h1) */
  @media only screen and (max-width:560px){
    .h1{font-size:clamp(25px,7.3vw,40px) !important;line-height:1.04 !important}
  }
  a{color:#8E2F6F}
</style>
</head>
<body style="margin:0;padding:0;background:#F7F4F0;-webkit-font-smoothing:antialiased;">
<div style="display:none;font-size:1px;color:#F7F4F0;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;">
  ${p.preheader}
  &#8203;&#847;&#8203;&#847;&#8203;&#847;&#8203;&#847;&#8203;&#847;&#8203;&#847;
</div>

<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#F7F4F0;">
<tr><td align="center" style="padding:32px 12px;">

<table role="presentation" class="wrap" width="600" cellpadding="0" cellspacing="0" border="0" style="width:600px;max-width:600px;background:#F8F6F2;">

  <!-- ── masthead: ink, the lockup, the acid rail ─────────────────────── -->
  <tr>
    <td bgcolor="#1B0D16" style="background:#1B0D16;padding:32px 40px 28px;">
      <a href="https://www.semora.com.au" style="text-decoration:none;">
      <img src="https://www.semora.com.au/assets/logo/png/Lockup_reverse_1600.png"
           width="228" height="43" alt="SEMORA STUDIO"
           style="display:block;border:0;outline:none;text-decoration:none;width:228px;height:auto;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-weight:600;font-size:32px;line-height:1.04;letter-spacing:-0.006em;text-transform:uppercase;color:#F8F6F2;">
      </a>
    </td>
  </tr>
  <tr><td bgcolor="#B4CC2E" style="background:#B4CC2E;font-size:0;line-height:0;height:4px;">&nbsp;</td></tr>

  <!-- ── kicker + title: the label voice, then the heading voice ─────── -->
  <tr>
    <td class="px" style="padding:40px 40px 0;">
      <p style="margin:0 0 12px;font-family:'Fragment Mono',Menlo,Consolas,monospace;font-weight:400;font-size:11px;line-height:1.62;letter-spacing:0.24em;text-transform:uppercase;color:#5D6B12;">
        ${p.kicker}
      </p>
      <h1 class="h1" style="margin:0 0 22px;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-weight:600;font-size:32px;line-height:1.04;letter-spacing:-0.006em;text-transform:uppercase;color:#1B0D16;">
        ${p.title}
      </h1>
    </td>
  </tr>

  <!-- ── body ─────────────────────────────────────────────────────────── -->
  ${p.body}

  <!-- ── footer: ink, the site's own sign-off, the locked NAP ─────────── -->
  <tr>
    <td class="px" bgcolor="#1B0D16" style="background:#1B0D16;padding:34px 40px 32px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
          <!-- the site footer's proportion: mark 64 beside a 240 lockup — 56 : 210 here -->
          <td valign="top" class="stack" width="72" style="width:72px;padding-right:16px;">
            <img src="https://www.semora.com.au/assets/logo/png/Mark_reverse_512.png"
                 width="56" height="56" alt=""
                 style="display:block;border:0;width:56px;height:auto;">
          </td>
          <td valign="top" class="stack">
            <img src="https://www.semora.com.au/assets/logo/png/Descriptor_reverse_1200.png"
                 width="210" height="67" alt="SEMORA — Specialist Practice Growth"
                 style="display:block;border:0;width:210px;height:auto;margin:0 0 14px;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-weight:600;font-size:15px;line-height:1.55;color:#F8F6F2;">
            <p style="margin:0 0 10px;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.55;color:#CFC4C9;">
              <strong style="color:#F8F6F2;">SEMORA STUDIO</strong> — a specialist
              growth company and marketing agency for commercial industry
              professionals, owner-led businesses, and healthcare and
              allied-health practices.
            </p>
            <!-- the locked NAP, one line, character for character (CLAUDE.md):
                 links carry the phone and the email, the visible text is the string -->
            <p style="margin:0 0 6px;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.55;color:#CFC4C9;">
              Central House Toorak, Level 3, 489 Toorak Road, Toorak VIC 3142 · <a href="tel:+61390710855" style="color:#F8F6F2;text-decoration:none;">(03) 9071 0855</a> · <a href="mailto:team@semora.com.au" style="color:#F8F6F2;text-decoration:none;">team@semora.com.au</a>
            </p>
            <p style="margin:0 0 10px;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.55;color:#CFC4C9;">
              <a href="https://www.semora.com.au" style="color:#F8F6F2;text-decoration:none;">semora.com.au</a>
            </p>
            <p style="margin:0;font-family:'Fragment Mono',Menlo,Consolas,monospace;font-weight:400;font-size:11px;line-height:1.62;letter-spacing:0.012em;text-transform:uppercase;color:#CFC4C9;">
              SEMORA STUDIO PTY LTD · ABN 77 701 244 635
            </p>
          </td>
        </tr>
      </table>
    </td>
  </tr>

</table>

<p style="margin:20px 0 0;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:13px;line-height:1.62;color:#6B6560;max-width:600px;">
  ${p.footnote}
</p>

</td></tr>
</table>
</body>
</html>
`;
}

export function autoReplyHtml(d) {
  const e = escapeHtml;
  const body = `<tr>
    <td class="px" style="padding:0 40px 10px;">
      <p style="margin:0 0 18px;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:17px;line-height:1.62;color:#424242;">
        Hello ${e(d.name)} — we have your enquiry and it has gone straight to a
        person, not a queue.
      </p>
      <p style="margin:0 0 18px;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:17px;line-height:1.62;color:#424242;">
        <strong style="color:#1B0D16;">${e(promise(d))}</strong>
        Response speed is one of the eleven surfaces we score, and we are
        scored on it too — so that is a commitment, not a courtesy.
      </p>
    </td>
  </tr>

  <!-- ── what happens next: ours, on the darkened-acid rail ──────────── -->
  <tr>
    <td class="px" style="padding:14px 40px 8px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-left:3px solid #5D6B12;">
        <tr><td style="padding:4px 0 4px 22px;">
          <p style="margin:0 0 12px;font-family:'Fragment Mono',Menlo,Consolas,monospace;font-weight:400;font-size:11px;line-height:1.62;letter-spacing:0.24em;text-transform:uppercase;color:#5D6B12;">
            What happens next /
          </p>
          <p style="margin:0 0 10px;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.55;color:#424242;">
            <strong style="color:#1B0D16;">1 ·</strong> We read what you sent and look at your current marketing before we reply.
          </p>
          <p style="margin:0 0 10px;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.55;color:#424242;">
            <strong style="color:#1B0D16;">2 ·</strong> You get a named person, a straight answer, and a number — never a discovery call to qualify you.
          </p>
          <p style="margin:0;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.55;color:#424242;">
            <strong style="color:#1B0D16;">3 ·</strong> If we are not the right fit, we will say so and tell you who is.
          </p>
        </td></tr>
      </table>
    </td>
  </tr>

  <!-- ── the call to action: the site's button on a light field ──────── -->
  <tr>
    <td class="px" style="padding:34px 40px 8px;">
      <p style="margin:0 0 20px;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:17px;line-height:1.62;color:#424242;">
        While you wait, score your own practice on the eleven surfaces buyers
        actually judge. It takes four minutes and you keep the result whether
        or not we work together.
      </p>
      <!--[if mso]>
      <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word"
        href="https://www.semora.com.au/score" style="height:61px;v-text-anchor:middle;width:253px;" arcsize="0%" stroke="f" fillcolor="#3F4A0C">
        <w:anchorlock/>
        <center style="color:#F8F6F2;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-weight:600;font-size:15px;line-height:1.62;letter-spacing:0.012em;text-transform:uppercase;">SCORE YOUR PRACTICE</center>
      </v:roundrect>
      <![endif]-->
      <!--[if !mso]><!-- -->
      <a href="https://www.semora.com.au/score"
         style="display:inline-block;background:#3F4A0C;color:#F8F6F2;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-weight:600;font-size:15px;line-height:1.62;letter-spacing:0.012em;text-transform:uppercase;text-decoration:none;padding:1.15em 2.2em;border:1px solid #3F4A0C;">
        Score your practice
      </a>
      <!--<![endif]-->
    </td>
  </tr>

  <!-- ── what you sent us ─────────────────────────────────────────────── -->
  <tr>
    <td class="px" style="padding:36px 40px 44px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-top:1px solid #DCD7CE;">
        <tr><td style="padding:24px 0 0;">
          <p style="margin:0 0 14px;font-family:'Fragment Mono',Menlo,Consolas,monospace;font-weight:400;font-size:11px;line-height:1.62;letter-spacing:0.24em;text-transform:uppercase;color:#5D6B12;">
            What you sent us /
          </p>
          <p style="margin:0 0 7px;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.62;color:#6B6560;">
            <span style="font-family:'Fragment Mono',Menlo,Consolas,monospace;font-size:11px;letter-spacing:0.012em;text-transform:uppercase;color:#5D6B12;">Practice</span> &nbsp;${e(d.practice)}
          </p>
          <p style="margin:0 0 7px;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.62;color:#6B6560;">
            <span style="font-family:'Fragment Mono',Menlo,Consolas,monospace;font-size:11px;letter-spacing:0.012em;text-transform:uppercase;color:#5D6B12;">Field</span> &nbsp;${e(d.vertical)}
          </p>
          <p style="margin:0 0 7px;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.62;color:#6B6560;">
            <span style="font-family:'Fragment Mono',Menlo,Consolas,monospace;font-size:11px;letter-spacing:0.012em;text-transform:uppercase;color:#5D6B12;">Wants</span> &nbsp;${e(d.want)}
          </p>
          <p style="margin:0;font-family:'Instrument Sans',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.62;color:#6B6560;">
            <span style="font-family:'Fragment Mono',Menlo,Consolas,monospace;font-size:11px;letter-spacing:0.012em;text-transform:uppercase;color:#5D6B12;">Note</span> &nbsp;${e(d.prompt)}
          </p>
        </td></tr>
      </table>
    </td>
  </tr>
`;
  return frame({
    preheader: 'We have your enquiry. ' + e(promise(d)),
    kicker: 'Your enquiry /',
    title: 'Thank you \u2014 that\u2019s with us.',
    body,
    footnote: 'You are receiving this because you sent an enquiry through semora.com.au.',
  });
}
