/* GENERATED by _build/build_site.py from _build/email/autoreply.html — do not edit. */

export function escapeHtml(s) {
  return String(s ?? '').replace(/[&<>"']/g, (c) => (
    { '&': '&amp;', '<': '&lt;', '>': '&gt;',
      '"': '&quot;', "'": '&#39;' }[c]));
}

export function autoReplyHtml(d) {
  const e = escapeHtml;
  return `<!doctype html>
<html lang="en-AU" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="x-apple-disable-message-reformatting">
<meta name="color-scheme" content="light">
<meta name="supported-color-schemes" content="light">
<title>Thank you — that’s with us</title>
<!--[if mso]>
<xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml>
<![endif]-->
<style>
  /* Only progressive enhancement lives here. Every style that matters is
     inlined below, because Gmail strips <style> in forwarded messages. */
  @media only screen and (max-width:620px){
    .wrap{width:100% !important}
    .px{padding-left:26px !important;padding-right:26px !important}
    .h1{font-size:30px !important;line-height:1.18 !important}
    .stack{display:block !important;width:100% !important}
  }
  a{color:#5B3A52}
</style>
</head>
<body style="margin:0;padding:0;background:#F0E8EC;-webkit-font-smoothing:antialiased;">
<div style="display:none;font-size:1px;color:#F0E8EC;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;">
  We have your enquiry. A named person replies within one business day.
  &#8203;&#847;&#8203;&#847;&#8203;&#847;&#8203;&#847;&#8203;&#847;&#8203;&#847;
</div>

<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#F0E8EC;">
<tr><td align="center" style="padding:32px 12px;">

<table role="presentation" class="wrap" width="600" cellpadding="0" cellspacing="0" border="0" style="width:600px;max-width:600px;background:#F8F6F2;">

  <!-- ── masthead ─────────────────────────────────────────────── -->
  <tr>
    <td bgcolor="#2E1C29" style="background:#2E1C29;padding:34px 40px 30px;">
      <img src="https://www.semora.com.au/assets/logo/png/Lockup_reverse_1600.png"
           width="228" height="43" alt="SEMORA STUDIO"
           style="display:block;border:0;outline:none;text-decoration:none;width:228px;height:auto;">
    </td>
  </tr>
  <tr><td bgcolor="#6B7B4E" style="background:#6B7B4E;font-size:0;line-height:0;height:4px;">&nbsp;</td></tr>

  <!-- ── body ─────────────────────────────────────────────────── -->
  <tr>
    <td class="px" style="padding:44px 40px 12px;">
      <p style="margin:0 0 10px;font-family:'IBM Plex Mono',Consolas,monospace;font-size:11px;letter-spacing:0.18em;text-transform:uppercase;color:#8B6B7E;">
        Your enquiry /
      </p>
      <h1 class="h1" style="margin:0 0 20px;font-family:Georgia,'Times New Roman',serif;font-weight:400;font-size:36px;line-height:1.15;letter-spacing:-0.01em;color:#2E1C29;">
        Thank you — that’s with us.
      </h1>
      <p style="margin:0 0 18px;font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.62;color:#424242;">
        Hello ${e(d.name)} — we have your enquiry and it has gone straight to a
        person, not a queue.
      </p>
      <p style="margin:0 0 18px;font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.62;color:#424242;">
        <strong style="color:#2E1C29;">You will hear back within one business day.</strong>
        Response speed is one of the eleven surfaces we score, and we are
        scored on it too — so that is a commitment, not a courtesy.
      </p>
    </td>
  </tr>

  <!-- ── what happens next ────────────────────────────────────── -->
  <tr>
    <td class="px" style="padding:14px 40px 8px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-left:3px solid #6B7B4E;">
        <tr><td style="padding:4px 0 4px 22px;">
          <p style="margin:0 0 12px;font-family:'IBM Plex Mono',Consolas,monospace;font-size:11px;letter-spacing:0.18em;text-transform:uppercase;color:#525E3A;">
            What happens next /
          </p>
          <p style="margin:0 0 10px;font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.6;color:#424242;">
            <strong style="color:#2E1C29;">1 ·</strong> We read what you sent and look at your current marketing before we reply.
          </p>
          <p style="margin:0 0 10px;font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.6;color:#424242;">
            <strong style="color:#2E1C29;">2 ·</strong> You get a named person, a straight answer, and a number — never a discovery call to qualify you.
          </p>
          <p style="margin:0;font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.6;color:#424242;">
            <strong style="color:#2E1C29;">3 ·</strong> If we are not the right fit, we will say so and tell you who is.
          </p>
        </td></tr>
      </table>
    </td>
  </tr>

  <!-- ── CTA ──────────────────────────────────────────────────── -->
  <tr>
    <td class="px" style="padding:34px 40px 8px;">
      <p style="margin:0 0 18px;font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.62;color:#424242;">
        While you wait, score your own practice on the eleven surfaces buyers
        actually judge. It takes four minutes and you keep the result whether
        or not we work together.
      </p>
      <!--[if mso]>
      <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word"
        href="https://www.semora.com.au/score" style="height:52px;v-text-anchor:middle;width:272px;" arcsize="0%" stroke="f" fillcolor="#3C2637">
        <w:anchorlock/>
        <center style="color:#F0E9DD;font-family:Arial,sans-serif;font-size:12px;letter-spacing:2px;">SCORE YOUR PRACTICE</center>
      </v:roundrect>
      <![endif]-->
      <!--[if !mso]><!-- -->
      <a href="https://www.semora.com.au/score"
         style="display:inline-block;background:#3C2637;color:#F0E9DD;font-family:'IBM Plex Mono',Consolas,monospace;font-size:12px;font-weight:500;letter-spacing:0.16em;text-transform:uppercase;text-decoration:none;padding:18px 32px;mso-hide:all;">
        Score your practice
      </a>
      <!--<![endif]-->
    </td>
  </tr>

  <!-- ── submission copy ──────────────────────────────────────── -->
  <tr>
    <td class="px" style="padding:36px 40px 44px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-top:1px solid #E7DCCB;">
        <tr><td style="padding:24px 0 0;">
          <p style="margin:0 0 14px;font-family:'IBM Plex Mono',Consolas,monospace;font-size:11px;letter-spacing:0.18em;text-transform:uppercase;color:#8B6B7E;">
            What you sent us /
          </p>
          <p style="margin:0 0 7px;font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:14px;line-height:1.6;color:#6B6560;">
            <span style="color:#8B6B7E;">Practice</span> &nbsp;${e(d.practice)}
          </p>
          <p style="margin:0 0 7px;font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:14px;line-height:1.6;color:#6B6560;">
            <span style="color:#8B6B7E;">Field</span> &nbsp;${e(d.vertical)}
          </p>
          <p style="margin:0 0 7px;font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:14px;line-height:1.6;color:#6B6560;">
            <span style="color:#8B6B7E;">Wants</span> &nbsp;${e(d.want)}
          </p>
          <p style="margin:0;font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:14px;line-height:1.6;color:#6B6560;">
            <span style="color:#8B6B7E;">Note</span> &nbsp;${e(d.prompt)}
          </p>
        </td></tr>
      </table>
    </td>
  </tr>

  <!-- ── footer ───────────────────────────────────────────────── -->
  <tr>
    <td class="px" bgcolor="#2E1C29" style="background:#2E1C29;padding:32px 40px;margin-top:40px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td valign="top" class="stack" width="52" style="width:52px;padding-right:18px;">
            <img src="https://www.semora.com.au/assets/logo/png/Mark_reverse_512.png"
                 width="34" height="45" alt=""
                 style="display:block;border:0;width:34px;height:auto;">
          </td>
          <td valign="top" class="stack">
            <p style="margin:0 0 8px;font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:13px;line-height:1.6;color:#D7C8D1;">
              <strong style="color:#F0E9DD;">SEMORA STUDIO</strong> — a specialist
              growth company and marketing agency for commercial industry
              professionals, owner-led businesses, and healthcare and
              allied-health practices.
            </p>
            <p style="margin:0 0 8px;font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:13px;line-height:1.6;color:#8B6B7E;">
              Central House Toorak, Level 3, 489 Toorak Road, Toorak VIC 3142<br>
              <a href="mailto:team@semora.com.au" style="color:#CFC0A8;text-decoration:none;">team@semora.com.au</a>
              &nbsp;·&nbsp;
              <a href="https://www.semora.com.au" style="color:#CFC0A8;text-decoration:none;">semora.com.au</a>
            </p>
            <p style="margin:0;font-family:'IBM Plex Mono',Consolas,monospace;font-size:10px;letter-spacing:0.12em;color:#8B6B7E;">
              SEMORA STUDIO PTY LTD · ABN 77 701 244 635
            </p>
          </td>
        </tr>
      </table>
    </td>
  </tr>

</table>

<p style="margin:22px 0 0;font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:11px;line-height:1.6;color:#8B6B7E;max-width:600px;">
  You are receiving this because you sent an enquiry through semora.com.au.
</p>

</td></tr>
</table>
</body>
</html>
`;
}
